import React, { useState } from 'react';
import { PaperData, ExperimentProject } from '../types';
import { 
  X, 
  Download, 
  Copy, 
  Check, 
  FileText, 
  Code, 
  Printer, 
  BookOpen, 
  Share2 
} from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  paperData: PaperData;
  experiment: ExperimentProject;
  hasAppliedAblation: boolean;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  paperData,
  experiment,
  hasAppliedAblation,
}) => {
  const [activeFormat, setActiveFormat] = useState<'latex' | 'markdown' | 'bibtex'>('latex');
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  // Generate LaTeX Source
  const generateLatex = () => {
    return `% ==============================================================================
% Spatial-Temporal Transformer for Urban EV Fast-Charging Load Forecasting
% Auto-generated by AI Paper Agent (IEEE / NeurIPS Format)
% ==============================================================================
\\documentclass[lettersize,journal]{IEEEtran}
\\usepackage{amsmath,amsfonts}
\\usepackage{algorithmic}
\\usepackage{algorithm}
\\usepackage{array}
\\usepackage{textcomp}
\\usepackage{stfloats}
\\usepackage{url}
\\usepackage{verbatim}
\\usepackage{graphicx}
\\usepackage{cite}
\\usepackage{booktabs}

\\begin{document}

\\title{${paperData.title}}

\\author{Katherine Vance, Marcus Chen, and Elena Rostova%
\\thanks{Institute of Smart Grid & Intelligent Transportation, University of Tech (e-mail: k.vance@tech.edu).}%
\\thanks{Department of Electrical Engineering, National Energy Laboratory.}}

\\maketitle

\\begin{abstract}
${paperData.abstract}
\\end{abstract}

\\begin{IEEEkeywords}
${paperData.keywords.join(', ')}.
\\end{IEEEkeywords}

\\section{Introduction}
${paperData.sections.find(s => s.id === 'sec-1')?.content}

\\section{Related Work}
${paperData.sections.find(s => s.id === 'sec-2')?.content}

\\section{Methodology}
${paperData.sections.find(s => s.id === 'sec-3')?.content}

\\section{Experiments}
\\subsection{Dataset \\& Experimental Setup}
${paperData.sections.find(s => s.id === 'sec-4')?.subsections?.find(sub => sub.id === 'sec-4-1')?.content}

\\subsection{Baseline Models}
${paperData.sections.find(s => s.id === 'sec-4')?.subsections?.find(sub => sub.id === 'sec-4-2')?.content}

\\subsection{Results \\& Comparative Analysis}
${paperData.sections.find(s => s.id === 'sec-4')?.subsections?.find(sub => sub.id === 'sec-4-3')?.content}

${hasAppliedAblation ? `\\subsection{Ablation Study}
To systematically verify component contributions, we isolate key mechanisms: w/o Weather (MAE 16.12 kW), w/o Dynamic Pricing (MAE 17.45 kW), and w/o Spatial Cross-Attention (MAE 18.05 kW).` : ''}

\\section{Discussion}
${paperData.sections.find(s => s.id === 'sec-5')?.content}

\\section{Conclusion}
${paperData.sections.find(s => s.id === 'sec-6')?.content}

\\begin{thebibliography}{99}
${paperData.references.map(r => `\\bibitem{ref${r.id}}\n${r.text}`).join('\n\n')}
\\end{thebibliography}

\\end{document}
`;
  };

  // Generate Markdown
  const generateMarkdown = () => {
    return `# ${paperData.title}

**Authors:** ${paperData.authors.map(a => `${a.name} (${a.institution})`).join(', ')}

---

### Abstract
${paperData.abstract}

**Keywords:** ${paperData.keywords.join(', ')}

---

## 1. Introduction
${paperData.sections.find(s => s.id === 'sec-1')?.content}

## 2. Related Work
${paperData.sections.find(s => s.id === 'sec-2')?.content}

## 3. Methodology
${paperData.sections.find(s => s.id === 'sec-3')?.content}

## 4. Experiments
${paperData.sections.find(s => s.id === 'sec-4')?.content}

### 4.1 Dataset & Experimental Setup
${paperData.sections.find(s => s.id === 'sec-4')?.subsections?.find(sub => sub.id === 'sec-4-1')?.content}

### 4.2 Baseline Models
${paperData.sections.find(s => s.id === 'sec-4')?.subsections?.find(sub => sub.id === 'sec-4-2')?.content}

### 4.3 Results & Comparative Analysis
${paperData.sections.find(s => s.id === 'sec-4')?.subsections?.find(sub => sub.id === 'sec-4-3')?.content}

${hasAppliedAblation ? `### 4.4 Ablation Study\nComprehensive ablation verifying Weather, Dynamic Pricing, and Spatial Cross-Attention contributions.` : ''}

## 5. Discussion
${paperData.sections.find(s => s.id === 'sec-5')?.content}

## 6. Conclusion
${paperData.sections.find(s => s.id === 'sec-6')?.content}

---

## References
${paperData.references.map(r => `[${r.id}] ${r.text}`).join('\n\n')}
`;
  };

  // Generate BibTeX
  const generateBibtex = () => {
    return `@article{vance2026spatial,
  title={Spatial-Temporal Transformer for Urban Electric Vehicle Fast-Charging Load Forecasting under Dynamic Pricing},
  author={Vance, Katherine and Chen, Marcus and Rostova, Elena},
  journal={IEEE Transactions on Smart Grid},
  volume={17},
  number={3},
  pages={2145--2158},
  year={2026},
  publisher={IEEE},
  doi={10.1109/TSG.2026.3190822}
}`;
  };

  const getActiveContent = () => {
    if (activeFormat === 'latex') return generateLatex();
    if (activeFormat === 'markdown') return generateMarkdown();
    return generateBibtex();
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveContent());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = activeFormat === 'latex' ? 'tex' : activeFormat === 'markdown' ? 'md' : 'bib';
    const blob = new Blob([getActiveContent()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AI_Paper_${experiment.id}_${new Date().toISOString().slice(0, 10)}.${ext}`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrintPDF = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-fadeIn">
      <div className="w-full max-w-3xl bg-slate-900 border border-slate-700/90 rounded-2xl shadow-2xl text-slate-100 overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-slate-800 bg-slate-950/60">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-lg bg-blue-600/20 text-cyan-400 border border-blue-500/30 flex items-center justify-center">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">导出学术论文 (Export Paper)</h2>
              <p className="text-xs text-slate-400">选择所需科研排版或源代码格式</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Format Selector Bar */}
        <div className="p-4 bg-slate-950/40 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center space-x-1.5">
            <button
              onClick={() => setActiveFormat('latex')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center space-x-1.5 transition ${
                activeFormat === 'latex'
                  ? 'bg-blue-600 text-white shadow'
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
              }`}
            >
              <Code className="w-3.5 h-3.5" />
              <span>LaTeX (.tex)</span>
            </button>

            <button
              onClick={() => setActiveFormat('markdown')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center space-x-1.5 transition ${
                activeFormat === 'markdown'
                  ? 'bg-blue-600 text-white shadow'
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Markdown (.md)</span>
            </button>

            <button
              onClick={() => setActiveFormat('bibtex')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center space-x-1.5 transition ${
                activeFormat === 'bibtex'
                  ? 'bg-blue-600 text-white shadow'
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
              }`}
            >
              <BookOpen className="w-3.5 h-3.5" />
              <span>BibTeX (.bib)</span>
            </button>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrintPDF}
              className="px-3 py-1.5 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 flex items-center space-x-1.5 transition"
            >
              <Printer className="w-3.5 h-3.5 text-cyan-400" />
              <span>打印 / 另存为 PDF</span>
            </button>

            <button
              onClick={handleCopy}
              className="px-3 py-1.5 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 flex items-center space-x-1.5 transition"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? '已复制' : '复制内容'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="px-3.5 py-1.5 text-xs font-bold text-white bg-blue-600 hover:bg-blue-500 rounded-lg shadow-md shadow-blue-600/30 flex items-center space-x-1.5 transition"
            >
              <Download className="w-3.5 h-3.5" />
              <span>下载文件</span>
            </button>
          </div>
        </div>

        {/* Code / Text Preview */}
        <div className="p-4 flex-1 overflow-y-auto font-mono text-xs text-slate-300 bg-slate-950 leading-relaxed select-all">
          <pre className="whitespace-pre-wrap">{getActiveContent()}</pre>
        </div>
      </div>
    </div>
  );
};
