import {
  ApiKeyItem,
  BillingRecord,
  ModelItem,
  PricingItem,
  ProviderItem,
  Permission,
  RecentRequest,
  RequestLogItem,
  RoleItem,
  StudentItem,
} from './types';

export const INITIAL_RECENT_REQUESTS: RecentRequest[] = [
  {
    id: 'req-001',
    model: 'gpt-4o',
    provider: 'OpenAI-US',
    inputTokens: 1250,
    outputTokens: 420,
    latencyMs: 142,
    costYuan: 0.048,
    status: 'success',
    timestamp: '2026-07-26 11:45:12',
  },
  {
    id: 'req-002',
    model: 'deepseek-v3',
    provider: 'DeepSeek-CN',
    inputTokens: 3400,
    outputTokens: 890,
    latencyMs: 98,
    costYuan: 0.008,
    status: 'success',
    timestamp: '2026-07-26 11:44:50',
  },
  {
    id: 'req-003',
    model: 'claude-3-5-sonnet',
    provider: 'Anthropic-Global',
    inputTokens: 820,
    outputTokens: 110,
    latencyMs: 310,
    costYuan: 0.035,
    status: 'failed',
    timestamp: '2026-07-26 11:43:08',
  },
  {
    id: 'req-004',
    model: 'gpt-4o-mini',
    provider: 'Azure-OpenAI',
    inputTokens: 520,
    outputTokens: 180,
    latencyMs: 85,
    costYuan: 0.003,
    status: 'success',
    timestamp: '2026-07-26 11:42:15',
  },
  {
    id: 'req-005',
    model: 'qwen-2-5-72b',
    provider: 'Aliyun-DashScope',
    inputTokens: 2100,
    outputTokens: 650,
    latencyMs: 112,
    costYuan: 0.012,
    status: 'success',
    timestamp: '2026-07-26 11:40:02',
  },
  {
    id: 'req-006',
    model: 'deepseek-r1',
    provider: 'DeepSeek-CN',
    inputTokens: 4120,
    outputTokens: 1540,
    latencyMs: 420,
    costYuan: 0.024,
    status: 'success',
    timestamp: '2026-07-26 11:38:22',
  },
];

export const INITIAL_API_KEYS: ApiKeyItem[] = [
  {
    id: 'key-1',
    prefix: 'nk_live_8f3a9a12',
    name: '生产环境 API Key',
    scope: '全部模型 (All)',
    status: 'active',
    createdAt: '2026-06-01 10:00:00',
  },
  {
    id: 'key-2',
    prefix: 'nk_test_7c2b14e9',
    name: '测试环境 API Key',
    scope: 'GPT-4o, DeepSeek-V3',
    status: 'active',
    createdAt: '2026-06-15 14:30:00',
  },
  {
    id: 'key-3',
    prefix: 'nk_dev_3e8f5211',
    name: '学生实习账号 Key',
    scope: '仅限开源基础模型',
    status: 'revoked',
    createdAt: '2026-05-20 09:12:00',
  },
  {
    id: 'key-4',
    prefix: 'nk_live_9a0c331f',
    name: '后端路由转发专用 Key',
    scope: '全部模型 (All)',
    status: 'active',
    createdAt: '2026-07-02 16:20:00',
  },
];

export const INITIAL_PROVIDERS: ProviderItem[] = [
  {
    id: 'prov-1',
    name: 'OpenAI Direct',
    baseUrl: 'https://api.openai.com/v1',
    apiPath: '/chat/completions',
    apiKeyRef: 'env:OPENAI_API_KEY_SEC',
    priority: 1,
    weight: 100,
    enabled: true,
  },
  {
    id: 'prov-2',
    name: 'DeepSeek Official',
    baseUrl: 'https://api.deepseek.com/v1',
    apiPath: '/chat/completions',
    apiKeyRef: 'env:DEEPSEEK_API_KEY',
    priority: 1,
    weight: 90,
    enabled: true,
  },
  {
    id: 'prov-3',
    name: 'Anthropic Claude',
    baseUrl: 'https://api.anthropic.com/v1',
    apiPath: '/messages',
    apiKeyRef: 'env:ANTHROPIC_KEY',
    priority: 2,
    weight: 80,
    enabled: true,
  },
  {
    id: 'prov-4',
    name: 'Azure OpenAI HK',
    baseUrl: 'https://nova-azure.openai.azure.com/openai/deployments',
    apiPath: '/completions?api-version=2024-02-15-preview',
    apiKeyRef: 'env:AZURE_OPENAI_KEY',
    priority: 3,
    weight: 50,
    enabled: false,
  },
];

export const INITIAL_MODELS: ModelItem[] = [
  {
    id: 'mod-1',
    name: 'GPT-4o Omni',
    code: 'gpt-4o',
    status: 'active',
    boundProviders: [
      { providerName: 'OpenAI Direct', weight: 80 },
      { providerName: 'Azure OpenAI HK', weight: 20 },
    ],
  },
  {
    id: 'mod-2',
    name: 'DeepSeek V3',
    code: 'deepseek-v3',
    status: 'active',
    boundProviders: [{ providerName: 'DeepSeek Official', weight: 100 }],
  },
  {
    id: 'mod-3',
    name: 'Claude 3.5 Sonnet',
    code: 'claude-3-5-sonnet',
    status: 'active',
    boundProviders: [{ providerName: 'Anthropic Claude', weight: 100 }],
  },
  {
    id: 'mod-4',
    name: 'GPT-4o Mini',
    code: 'gpt-4o-mini',
    status: 'active',
    boundProviders: [{ providerName: 'OpenAI Direct', weight: 100 }],
  },
  {
    id: 'mod-5',
    name: 'Qwen 2.5 72B',
    code: 'qwen-2-5-72b',
    status: 'inactive',
    boundProviders: [], // Unbound example
  },
];

export const INITIAL_PRICING: PricingItem[] = [
  {
    id: 'prc-1',
    modelName: 'GPT-4o Omni',
    modelCode: 'gpt-4o',
    pricingType: 'unified',
    inputPrice: 0.018,
    outputPrice: 0.072,
  },
  {
    id: 'prc-2',
    modelName: 'DeepSeek V3',
    modelCode: 'deepseek-v3',
    pricingType: 'timebased',
    inputPrice: 0.002,
    outputPrice: 0.008,
    peakStartTime: '09:00',
    peakEndTime: '21:00',
    peakInputPrice: 0.003,
    peakOutputPrice: 0.012,
    offPeakInputPrice: 0.001,
    offPeakOutputPrice: 0.004,
  },
  {
    id: 'prc-3',
    modelName: 'Claude 3.5 Sonnet',
    modelCode: 'claude-3-5-sonnet',
    pricingType: 'unified',
    inputPrice: 0.022,
    outputPrice: 0.088,
  },
  {
    id: 'prc-4',
    modelName: 'GPT-4o Mini',
    modelCode: 'gpt-4o-mini',
    pricingType: 'timebased',
    inputPrice: 0.001,
    outputPrice: 0.004,
    peakStartTime: '08:00',
    peakEndTime: '20:00',
    peakInputPrice: 0.0015,
    peakOutputPrice: 0.005,
    offPeakInputPrice: 0.0008,
    offPeakOutputPrice: 0.0025,
  },
];

export const INITIAL_BILLING_RECORDS: BillingRecord[] = [
  {
    id: 'bil-101',
    email: 'zhangsan@university.edu.cn',
    modelCode: 'gpt-4o',
    inputTokens: 15400,
    outputTokens: 4200,
    costYuan: 0.58,
    status: 'success',
    timestamp: '2026-07-26 11:30:15',
  },
  {
    id: 'bil-102',
    email: 'lisi@nova-lab.com',
    modelCode: 'deepseek-v3',
    inputTokens: 89000,
    outputTokens: 24000,
    costYuan: 0.27,
    status: 'success',
    timestamp: '2026-07-26 11:22:04',
  },
  {
    id: 'bil-103',
    email: 'wangwu@student.tsinghua.edu.cn',
    modelCode: 'claude-3-5-sonnet',
    inputTokens: 3200,
    outputTokens: 0,
    costYuan: 0.0,
    status: 'failed',
    timestamp: '2026-07-26 11:15:42',
  },
  {
    id: 'bil-104',
    email: 'zhaoliu@ai-research.org',
    modelCode: 'gpt-4o-mini',
    inputTokens: 42000,
    outputTokens: 18500,
    costYuan: 0.12,
    status: 'success',
    timestamp: '2026-07-26 10:55:18',
  },
  {
    id: 'bil-105',
    email: 'chenqi@tech-corp.cn',
    modelCode: 'qwen-2-5-72b',
    inputTokens: 120000,
    outputTokens: 35000,
    costYuan: 0.86,
    status: 'success',
    timestamp: '2026-07-26 10:40:00',
  },
];

export const INITIAL_REQUEST_LOGS: RequestLogItem[] = [
  {
    id: 'log-801',
    modelCode: 'gpt-4o',
    providerName: 'OpenAI Direct',
    inputTokens: 2450,
    outputTokens: 680,
    latencyMs: 165,
    costYuan: 0.093,
    status: 'success',
    timestamp: '2026-07-26 11:46:01',
    clientIp: '192.168.1.102',
  },
  {
    id: 'log-802',
    modelCode: 'deepseek-v3',
    providerName: 'DeepSeek Official',
    inputTokens: 12400,
    outputTokens: 3100,
    latencyMs: 110,
    costYuan: 0.037,
    status: 'success',
    timestamp: '2026-07-26 11:45:22',
    clientIp: '10.0.4.15',
  },
  {
    id: 'log-803',
    modelCode: 'claude-3-5-sonnet',
    providerName: 'Anthropic Claude',
    inputTokens: 850,
    outputTokens: 0,
    latencyMs: 520,
    costYuan: 0.0,
    status: 'failed',
    timestamp: '2026-07-26 11:42:19',
    clientIp: '172.16.0.8',
    errorMessage: 'Provider timeout error (504 Gateway Time-out)',
  },
  {
    id: 'log-804',
    modelCode: 'gpt-4o-mini',
    providerName: 'Azure OpenAI HK',
    inputTokens: 610,
    outputTokens: 210,
    latencyMs: 78,
    costYuan: 0.003,
    status: 'success',
    timestamp: '2026-07-26 11:39:50',
    clientIp: '192.168.1.108',
  },
  {
    id: 'log-805',
    modelCode: 'deepseek-v3',
    providerName: 'DeepSeek Official',
    inputTokens: 4800,
    outputTokens: 1200,
    latencyMs: 92,
    costYuan: 0.014,
    status: 'success',
    timestamp: '2026-07-26 11:35:10',
    clientIp: '10.0.4.22',
  },
];

export const INITIAL_STUDENTS: StudentItem[] = [
  {
    id: 'stu-1',
    email: 'zhangsan@university.edu.cn',
    nickname: '张三',
    status: 'enabled',
    quotaBalance: 150.0,
    createdAt: '2026-05-10 14:20',
    allowedModels: ['gpt-4o', 'deepseek-v3', 'gpt-4o-mini'],
  },
  {
    id: 'stu-2',
    email: 'lisi@nova-lab.com',
    nickname: '李四',
    status: 'enabled',
    quotaBalance: 500.5,
    createdAt: '2026-06-01 09:15',
    allowedModels: ['gpt-4o', 'deepseek-v3', 'claude-3-5-sonnet', 'gpt-4o-mini'],
  },
  {
    id: 'stu-3',
    email: 'wangwu@student.tsinghua.edu.cn',
    nickname: '王五',
    status: 'disabled',
    quotaBalance: 0.0,
    createdAt: '2026-06-20 18:00',
    allowedModels: ['gpt-4o-mini'],
  },
];

export const ALL_PERMISSIONS: Permission[] = [
  { code: 'apikey:read', name: 'API Key 查看', category: 'API Key 管理' },
  { code: 'apikey:manage', name: 'API Key 创建与撤销', category: 'API Key 管理' },
  { code: 'provider:read', name: 'Provider 列表查看', category: 'Provider 管理' },
  { code: 'provider:manage', name: 'Provider 编辑与删改', category: 'Provider 管理' },
  { code: 'model:read', name: '模型查看', category: '模型管理' },
  { code: 'model:manage', name: '模型配置与路由绑定', category: '模型管理' },
  { code: 'pricing:manage', name: '定价费率调整', category: '计费管理' },
  { code: 'billing:read', name: '账单与用量审计', category: '计费管理' },
  { code: 'student:manage', name: '学生额度与权限控制', category: '学生管理' },
  { code: 'role:manage', name: '角色与RBAC权限设置', category: '系统安全' },
];

export const INITIAL_ROLES: RoleItem[] = [
  {
    id: 'role-admin',
    name: '超级管理员',
    description: '具备平台最高权限，可管理所有系统配置、节点路由、费率及权限分配。',
    isSystem: true,
    permissionCount: 10,
    userCount: 2,
    createdAt: '2026-01-01 00:00',
    permissions: ALL_PERMISSIONS.map((p) => p.code),
  },
  {
    id: 'role-operator',
    name: '运维人员',
    description: '负责 Provider 监控、模型路由绑定、日志审计与延迟优化。',
    isSystem: false,
    permissionCount: 6,
    userCount: 5,
    createdAt: '2026-03-10 11:30',
    permissions: [
      'provider:read',
      'provider:manage',
      'model:read',
      'model:manage',
      'billing:read',
      'apikey:read',
    ],
  },
  {
    id: 'role-auditor',
    name: '财务审计员',
    description: '仅允许查看账单报表、请求日志及定价配置，不可进行破坏性删改。',
    isSystem: false,
    permissionCount: 3,
    userCount: 3,
    createdAt: '2026-04-15 16:40',
    permissions: ['pricing:manage', 'billing:read', 'model:read'],
  },
];
