<script setup lang="ts">
import { ref, computed } from 'vue'
import { X, Download, Copy, Check, FileText, Code, Printer, BookOpen } from 'lucide-vue-next'
import type { PaperData, ExperimentProject } from '@/data/paperAgentData'

const props = defineProps<{
  isOpen: boolean
  paperData: PaperData
  experiment: ExperimentProject
  hasAppliedAblation: boolean
}>()

const emit = defineEmits<{ (e: 'close'): void }>()

type ExportFormat = 'latex' | 'markdown' | 'bibtex'
const activeFormat = ref<ExportFormat>('latex')
const copied = ref(false)
let copyTimer: ReturnType<typeof setTimeout> | null = null

// ---------------------------------------------------------------- 模板生成

const generateLatex = () => {
  const findSec = (id: string) => props.paperData.sections.find((s) => s.id === id)?.content ?? ''
  const findSub = (subId: string) =>
    props.paperData.sections.find((s) => s.id === 'sec-4')?.subsections?.find((sub) => sub.id === subId)?.content ?? ''
  return `% ==============================================================================
% Spatial-Temporal Transformer for Urban EV Fast-Charging Load Forecasting
% Auto-generated by AI Paper Agent (IEEE / NeurIPS Format)
% ==============================================================================
\\documentclass[lettersize,journal]{IEEEtran}
\\usepackage{amsmath,amsfonts}
\\usepackage{algorithmic}
\\usepackage{algorithm}
\\usepackage{array}
\\usepackage{textcomp}
\\usepackage{stfloats}
\\usepackage{url}
\\usepackage{verbatim}
\\usepackage{graphicx}
\\usepackage{cite}
\\usepackage{booktabs}

\\begin{document}

\\title{${props.paperData.title}}

\\author{Katherine Vance, Marcus Chen, and Elena Rostova%
\\thanks{Institute of Smart Grid & Intelligent Transportation, University of Tech (e-mail: k.vance@tech.edu).}%
\\thanks{Department of Electrical Engineering, National Energy Laboratory.}}

\\maketitle

\\begin{abstract}
${props.paperData.abstract}
\\end{abstract}

\\begin{IEEEkeywords}
${props.paperData.keywords.join(', ')}.
\\end{IEEEkeywords}

\\section{Introduction}
${findSec('sec-1')}

\\section{Related Work}
${findSec('sec-2')}

\\section{Methodology}
${findSec('sec-3')}

\\section{Experiments}
\\subsection{Dataset \\& Experimental Setup}
${findSub('sec-4-1')}

\\subsection{Baseline Models}
${findSub('sec-4-2')}

\\subsection{Results \\& Comparative Analysis}
${findSub('sec-4-3')}

${props.hasAppliedAblation ? `\\subsection{Ablation Study}
To systematically verify component contributions, we isolate key mechanisms: w/o Weather (MAE 16.12 kW), w/o Dynamic Pricing (MAE 17.45 kW), and w/o Spatial Cross-Attention (MAE 18.05 kW).` : ''}

\\section{Discussion}
${findSec('sec-5')}

\\section{Conclusion}
${findSec('sec-6')}

\\begin{thebibliography}{99}
${props.paperData.references.map((r) => `\\bibitem{ref${r.id}}\n${r.text}`).join('\n\n')}
\\end{thebibliography}

\\end{document}
`
}

const generateMarkdown = () => {
  const findSec = (id: string) => props.paperData.sections.find((s) => s.id === id)?.content ?? ''
  const findSub = (subId: string) =>
    props.paperData.sections.find((s) => s.id === 'sec-4')?.subsections?.find((sub) => sub.id === subId)?.content ?? ''
  return `# ${props.paperData.title}

**Authors:** ${props.paperData.authors.map((a) => `${a.name} (${a.institution})`).join(', ')}

---

### Abstract
${props.paperData.abstract}

**Keywords:** ${props.paperData.keywords.join(', ')}

---

## 1. Introduction
${findSec('sec-1')}

## 2. Related Work
${findSec('sec-2')}

## 3. Methodology
${findSec('sec-3')}

## 4. Experiments
${findSec('sec-4')}

### 4.1 Dataset & Experimental Setup
${findSub('sec-4-1')}

### 4.2 Baseline Models
${findSub('sec-4-2')}

### 4.3 Results & Comparative Analysis
${findSub('sec-4-3')}

${props.hasAppliedAblation ? `### 4.4 Ablation Study\nComprehensive ablation verifying Weather, Dynamic Pricing, and Spatial Cross-Attention contributions.` : ''}

## 5. Discussion
${findSec('sec-5')}

## 6. Conclusion
${findSec('sec-6')}

---

## References
${props.paperData.references.map((r) => `[${r.id}] ${r.text}`).join('\n\n')}
`
}

const generateBibtex = () => `@article{vance2026spatial,
  title={Spatial-Temporal Transformer for Urban Electric Vehicle Fast-Charging Load Forecasting under Dynamic Pricing},
  author={Vance, Katherine and Chen, Marcus and Rostova, Elena},
  journal={IEEE Transactions on Smart Grid},
  volume={17},
  number={3},
  pages={2145--2158},
  year={2026},
  publisher={IEEE},
  doi={10.1109/TSG.2026.3190822}
}`

const activeContent = computed(() => {
  if (activeFormat.value === 'latex') return generateLatex()
  if (activeFormat.value === 'markdown') return generateMarkdown()
  return generateBibtex()
})

// ---------------------------------------------------------------- 交互

const handleCopy = () => {
  navigator.clipboard.writeText(activeContent.value)
  copied.value = true
  if (copyTimer) clearTimeout(copyTimer)
  copyTimer = setTimeout(() => (copied.value = false), 2000)
}

const handleDownload = () => {
  const ext = activeFormat.value === 'latex' ? 'tex' : activeFormat.value === 'markdown' ? 'md' : 'bib'
  const blob = new Blob([activeContent.value], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `AI_Paper_${props.experiment.id}_${new Date().toISOString().slice(0, 10)}.${ext}`
  link.click()
  URL.revokeObjectURL(url)
}

const handlePrintPDF = () => {
  window.print()
}
</script>

<template>
  <Teleport to="body">
    <div
      v-if="isOpen"
      class="fixed inset-0 z-[80] flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm"
      @click.self="emit('close')"
    >
      <div class="w-full max-w-3xl bg-slate-900 border border-slate-700/90 rounded-2xl shadow-2xl text-slate-100 overflow-hidden flex flex-col max-h-[90vh]">
        <!-- Header -->
        <div class="flex items-center justify-between p-5 border-b border-slate-800 bg-slate-950/60">
          <div class="flex items-center gap-2.5">
            <div class="w-8 h-8 rounded-lg bg-blue-600/20 text-cyan-400 border border-blue-500/30 flex items-center justify-center">
              <Download class="w-4 h-4" />
            </div>
            <div>
              <h2 class="text-base font-bold text-white">导出学术论文 (Export Paper)</h2>
              <p class="text-xs text-slate-400">选择所需科研排版或源代码格式</p>
            </div>
          </div>

          <button
            @click="emit('close')"
            class="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition"
          >
            <X class="w-5 h-5" />
          </button>
        </div>

        <!-- Format Selector Bar -->
        <div class="p-4 bg-slate-950/40 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div class="flex items-center gap-1.5">
            <button
              @click="activeFormat = 'latex'"
              class="px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition"
              :class="activeFormat === 'latex' ? 'bg-blue-600 text-white shadow' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'"
            >
              <Code class="w-3.5 h-3.5" />
              <span>LaTeX (.tex)</span>
            </button>

            <button
              @click="activeFormat = 'markdown'"
              class="px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition"
              :class="activeFormat === 'markdown' ? 'bg-blue-600 text-white shadow' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'"
            >
              <FileText class="w-3.5 h-3.5" />
              <span>Markdown (.md)</span>
            </button>

            <button
              @click="activeFormat = 'bibtex'"
              class="px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition"
              :class="activeFormat === 'bibtex' ? 'bg-blue-600 text-white shadow' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'"
            >
              <BookOpen class="w-3.5 h-3.5" />
              <span>BibTeX (.bib)</span>
            </button>
          </div>

          <div class="flex items-center gap-2">
            <button
              @click="handlePrintPDF"
              class="px-3 py-1.5 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 flex items-center gap-1.5 transition"
            >
              <Printer class="w-3.5 h-3.5 text-cyan-400" />
              <span>打印 / 另存为 PDF</span>
            </button>

            <button
              @click="handleCopy"
              class="px-3 py-1.5 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 flex items-center gap-1.5 transition"
            >
              <Check v-if="copied" class="w-3.5 h-3.5 text-emerald-400" />
              <Copy v-else class="w-3.5 h-3.5" />
              <span>{{ copied ? '已复制' : '复制内容' }}</span>
            </button>

            <button
              @click="handleDownload"
              class="px-3.5 py-1.5 text-xs font-bold text-white bg-blue-600 hover:bg-blue-500 rounded-lg shadow-md shadow-blue-600/30 flex items-center gap-1.5 transition"
            >
              <Download class="w-3.5 h-3.5" />
              <span>下载文件</span>
            </button>
          </div>
        </div>

        <!-- Code / Text Preview -->
        <div class="p-4 flex-1 overflow-y-auto font-mono text-xs text-slate-300 bg-slate-950 leading-relaxed select-all">
          <pre class="whitespace-pre-wrap">{{ activeContent }}</pre>
        </div>
      </div>
    </div>
  </Teleport>
</template>
