import React, { useState } from 'react';
import { 
  FileText, 
  X, 
  Copy, 
  Check, 
  Download, 
  FileDown, 
  Code, 
  Layers, 
  CheckCircle2
} from 'lucide-react';
import { PAPER_DRAFT_TEXT } from '../data/mockData';

interface PaperWritingModalProps {
  isOpen: boolean;
  onClose: () => void;
  datasetName?: string;
  includedFigures?: Array<{ id: string; title: string; caption: string }>;
}

export const PaperWritingModal: React.FC<PaperWritingModalProps> = ({
  isOpen,
  onClose,
  datasetName = 'experiment_result.xlsx',
}) => {
  const [styleFormat, setStyleFormat] = useState<'nature' | 'apa' | 'ieee'>('nature');
  const [language, setLanguage] = useState<'zh' | 'en'>('zh');
  const [copiedType, setCopiedType] = useState<'latex' | 'md' | null>(null);

  if (!isOpen) return null;

  const currentContent = PAPER_DRAFT_TEXT[language];

  const handleCopy = (text: string, type: 'latex' | 'md') => {
    if (type === 'latex') {
      const latexText = `% ===================================================
% SECTION: 3. RESULTS & STATISTICAL ANALYSIS
% Generated by AI Scientific Agent
% Dataset: ${datasetName} (N = 186,420, 42 features)
% ===================================================

\\section{Results}
\\label{sec:results}

\\subsection{Experimental Group Comparison and Main Effects}
Based on the high-throughput experimental dataset ($N = 186{,}420$), we observed a statistically significant performance variation across the three independent experimental conditions ($F(2, 186417) = 428.6, p < 0.001$, one-way ANOVA). Post-hoc Tukey's honestly significant difference (HSD) tests revealed that \\textbf{Group C} achieved the highest mean score ($91.2 \\pm 3.1$, 95\\% CI: $[90.5, 91.9]$), representing a $+16.33\\%$ relative gain compared to baseline \\textbf{Group A} ($78.4 \\pm 4.8$, 95\\% CI: $[77.2, 79.6]$, Cohen's $d = 3.18$). Group B also showed significant enhancement ($84.7 \\pm 3.9$, $+8.04\\%$, $p < 0.001$).

\\subsection{Distributional Stability and Reaction Dynamics}
Gaussian kernel density estimation confirmed a marked rightward peak shift and a $35.4\\%$ reduction in dispersion for Group C (coefficient of variation $\\mathrm{CV} = 3.4\\%$, Figure~1B). Time-course kinetic analysis over 12 hours demonstrated that Group C accelerated initial reaction velocity ($k_{\\mathrm{rate}} = 1.64\\times$) before converging to high steady-state yield.

\\subsection{Anomaly Diagnosis and Robustness Check}
Isolation Forest identified 23 multi-dimensional outliers (Sample \\#12842, \\#45109, \\#98231). Sensitivity re-estimation following outlier exclusion induced negligible perturbation ($< 0.3\\%$ in effect size), verifying the robustness of the primary findings.`;
      navigator.clipboard.writeText(latexText);
    } else {
      navigator.clipboard.writeText(text);
    }

    setCopiedType(type);
    setTimeout(() => setCopiedType(null), 2000);
  };

  const handleDownloadDoc = () => {
    const element = document.createElement('a');
    const file = new Blob([currentContent], { type: 'text/markdown;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = `Paper_Results_Draft_${styleFormat.toUpperCase()}_${language}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-[#050505]/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-5xl h-[90vh] bg-[#0f172a] border border-[#1e293b] rounded-xl shadow-2xl flex flex-col overflow-hidden">
        {/* Modal Top Bar */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-[#1e293b] bg-black/40">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-blue-500/10 border border-blue-500/30 flex items-center justify-center">
              <FileText className="w-5 h-5 text-blue-400" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base sm:text-lg font-bold text-white tracking-tight">
                  论文写作 (Paper Results Generator)
                </h3>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/30">
                  Ready to Publish
                </span>
              </div>
              <p className="text-xs text-[#94a3b8]">
                已根据 18.6 万条实验数据自动组织 SCI 顶刊 Results 标准章节与图表引用
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg bg-black/40 hover:bg-[#1e293b] text-[#94a3b8] hover:text-white border border-[#1e293b] flex items-center justify-center transition-colors cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Toolbar Settings */}
        <div className="px-5 py-3 border-b border-[#1e293b] bg-black/20 flex flex-wrap items-center justify-between gap-3 text-xs">
          {/* Format Selector */}
          <div className="flex items-center gap-2">
            <span className="text-[#94a3b8] font-medium">期刊规范:</span>
            {(['nature', 'apa', 'ieee'] as const).map((fmt) => (
              <button
                key={fmt}
                onClick={() => setStyleFormat(fmt)}
                className={`px-2.5 py-1 rounded uppercase font-mono transition-colors cursor-pointer ${
                  styleFormat === fmt
                    ? 'bg-blue-600/30 text-blue-400 font-bold border border-blue-500/40'
                    : 'text-[#64748b] hover:text-white bg-black/40 border border-[#1e293b]'
                }`}
              >
                {fmt}
              </button>
            ))}
          </div>

          {/* Language Selector */}
          <div className="flex items-center gap-2">
            <span className="text-[#94a3b8] font-medium">语言:</span>
            <button
              onClick={() => setLanguage('zh')}
              className={`px-2.5 py-1 rounded text-xs transition-colors cursor-pointer ${
                language === 'zh'
                  ? 'bg-blue-600/30 text-blue-400 font-bold border border-blue-500/40'
                  : 'text-[#64748b] hover:text-white bg-black/40 border border-[#1e293b]'
              }`}
            >
              中文 (学术规范)
            </button>
            <button
              onClick={() => setLanguage('en')}
              className={`px-2.5 py-1 rounded text-xs transition-colors cursor-pointer ${
                language === 'en'
                  ? 'bg-blue-600/30 text-blue-400 font-bold border border-blue-500/40'
                  : 'text-[#64748b] hover:text-white bg-black/40 border border-[#1e293b]'
              }`}
            >
              English (SCI Format)
            </button>
          </div>

          {/* Quick Copy Buttons */}
          <div className="flex items-center gap-2">
            <button
              onClick={() => handleCopy(currentContent, 'latex')}
              className="px-3 py-1.5 rounded bg-black/40 hover:bg-[#1e293b] text-slate-300 font-mono text-xs flex items-center gap-1.5 border border-[#1e293b] transition-colors cursor-pointer"
            >
              {copiedType === 'latex' ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="text-emerald-400 font-bold">已复制 LaTeX</span>
                </>
              ) : (
                <>
                  <Code className="w-3.5 h-3.5 text-blue-400" />
                  <span>复制 LaTeX 源码</span>
                </>
              )}
            </button>

            <button
              onClick={() => handleCopy(currentContent, 'md')}
              className="px-3 py-1.5 rounded bg-black/40 hover:bg-[#1e293b] text-slate-300 font-mono text-xs flex items-center gap-1.5 border border-[#1e293b] transition-colors cursor-pointer"
            >
              {copiedType === 'md' ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="text-emerald-400 font-bold">已复制 MD</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5 text-blue-400" />
                  <span>复制 Markdown</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownloadDoc}
              className="px-3 py-1.5 rounded bg-blue-600 hover:bg-blue-500 text-white font-medium text-xs flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <FileDown className="w-3.5 h-3.5" />
              <span>下载文稿 (.md)</span>
            </button>
          </div>
        </div>

        {/* Paper Document Preview Simulation */}
        <div className="flex-1 p-4 sm:p-6 overflow-y-auto bg-[#050505] flex justify-center">
          <div className="w-full max-w-3xl paper-page bg-[#0f172a] rounded-xl border border-[#1e293b] p-6 sm:p-10 font-serif text-[#e2e8f0] leading-relaxed text-sm sm:text-base space-y-6">
            {/* Header info */}
            <div className="border-b border-[#1e293b] pb-4 flex items-center justify-between font-sans text-xs text-[#94a3b8]">
              <span className="font-mono uppercase tracking-wider text-blue-400">
                Manuscript Section: 3. Results &amp; Statistical Analysis
              </span>
              <span>Dataset: {datasetName}</span>
            </div>

            {/* Content rendered nicely with highlighting */}
            <div className="space-y-4 text-[#e2e8f0]">
              <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
                3. Results
              </h2>

              <h3 className="text-base sm:text-lg font-bold text-blue-300 mt-4">
                3.1 实验组性能对比与主效应显著性
              </h3>
              <p className="leading-relaxed text-justify">
                本次研究基于大规模高通量实验数据集（<span className="font-mono text-blue-400">N = 186,420</span>，涵盖 42 个物理、化学与动力学特征维度），在完成数据缺失值无偏链式插补（MICE 算法）与全域噪声清洗后，对三个平行对照实验组展开了系统的统计推断与性能评估（<span className="font-bold text-blue-400 cursor-pointer hover:underline">Figure 1A</span>）。
              </p>
              <p className="leading-relaxed text-justify">
                单因素方差分析（One-way ANOVA）结果表明，各实验组间存在极显著的统计学主效应差异（<span className="font-mono font-bold text-emerald-400">F(2, 186417) = 428.6, p &lt; 0.001</span>）。事后 Tukey's HSD 多重比对分析进一步证实，<strong className="text-white">实验组 C</strong> 展现出最优的性能水平（均值：<span className="font-mono text-white">91.2 ± 3.1</span>，95% CI: [90.5, 91.9]），相较基准实验组 A（均值：<span className="font-mono text-white">78.4 ± 4.8</span>，95% CI: [77.2, 79.6]）实现了净增 <span className="font-bold text-emerald-400 font-mono">+16.33%</span> 的性能跃升（效应量 Cohen's d = 3.18）。此外，实验组 B（84.7 ± 3.9）相较组 A 提升 8.04%（p &lt; 0.001），而组 C 相较组 B 仍有极其显著的梯次增强（p &lt; 0.0001，Cohen's d = 1.84）。
              </p>

              <h3 className="text-base sm:text-lg font-bold text-blue-300 mt-6">
                3.2 概率密度分布与反应动力学历程
              </h3>
              <p className="leading-relaxed text-justify">
                高斯核密度分布估计（<span className="font-bold text-blue-400 cursor-pointer hover:underline">Figure 1B</span>）表明，实验组 C 的概率密度峰型显著右移，且方差离散度相较组 A 缩窄约 35.4%（离散系数 CV = 3.4%），证实协同催化体系在大幅提升响应强度的同时抑制了工况波动。12 小时反应动力学时序曲线（<span className="font-bold text-blue-400 cursor-pointer hover:underline">Figure 1C</span>）显示，实验组 C 在前 4 小时内即展现出陡峭的活化速率，随后平稳收敛至高转化率稳态。
              </p>

              <h3 className="text-base sm:text-lg font-bold text-blue-300 mt-6">
                3.3 孤立森林异常检测与敏感性复核
              </h3>
              <p className="leading-relaxed text-justify">
                通过全局 Isolation Forest 孤立森林与 3-Sigma 边界联合扫描，在全量样本中共定位 23 个异常样本点（<span className="font-bold text-blue-400 cursor-pointer hover:underline">Figure 1D</span>），重点包括 <span className="font-mono text-red-400">Sample #12842</span>（瞬态超温 137℃）、<span className="font-mono text-red-400">Sample #45109</span>（产率骤降至 31.2%）以及 <span className="font-mono text-red-400">Sample #98231</span>（瞬态背压 7.84 MPa）。在剔除该部分离群样本后的敏感性重估检验中，组间核心差异与 F 统计量波动小于 0.3%，证明了本研究结论的极高稳健性与学术复现力。
              </p>
            </div>

            {/* Figures Included Box */}
            <div className="mt-8 p-4 rounded-xl bg-black/40 border border-[#1e293b] font-sans text-xs text-[#94a3b8] space-y-2">
              <div className="font-bold text-white flex items-center gap-1.5">
                <Layers className="w-4 h-4 text-blue-400" />
                <span>已绑定并交叉引用的学术图表清单</span>
              </div>
              <ul className="list-disc pl-5 space-y-1 font-mono text-[11px] text-[#cbd5e1]">
                <li>Fig. 1A: 实验组对比图 (Bar chart with error bars, n=62,140/group, p &lt; 0.001)</li>
                <li>Fig. 1B: 指标分布图 (Gaussian Kernel Density Estimation curves)</li>
                <li>Fig. 1C: 动力学时序趋势图 (Time-course kinetics from 0h to 12h)</li>
                <li>Fig. 1D: 异常值残差散点图 (Isolation Forest &amp; 3-Sigma envelope)</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-5 py-3 border-t border-[#1e293b] bg-black/40 flex items-center justify-between text-xs text-[#94a3b8]">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span>符合《Nature》《Science》期刊实验结果 (Results) 章节写作规范</span>
          </div>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded bg-black/40 hover:bg-[#1e293b] text-white font-medium border border-[#1e293b] transition-colors cursor-pointer"
          >
            完成
          </button>
        </div>
      </div>
    </div>
  );
};
